// R16：只在 PACK_FIXTURES=1 时注册的运行时假包，不复用旅游工具或阶段规则。
import { deepFreeze, type IndustryPack, type PackRuntime, type SalesStage } from '../../core/pack-api.js';

export const fixture: IndustryPack = deepFreeze({
  id: '__fixture',
  name: '运行时假包',
  entities: [],
  vocabulary: { customer: '客户', advisor: '顾问', productNoun: '服务', tools: { fixture_inspect: '核验' }, sopFields: {} },
  sopSections: [],
  nav: { catalogGroup: '服务', entities: [] },
  stages: [
    { key: 'greeting', label: '开始' },
    { key: 'objection', label: '核验完成' },
  ],
});

export function createFixtureRuntime(): PackRuntime {
  return {
    id: fixture.id,
    defaultBrand: {
      brandName: '测试服务',
      advisorTitle: '顾问',
      aiTitle: 'AI 顾问',
      scopeNoun: '服务',
      identityLine: '我是测试服务的 AI 顾问',
    },
    legacy: {
      offTopicReply: '请说明服务需求',
      welcomeText: '欢迎咨询测试服务',
      welcomeBackText: '欢迎回来',
      webWelcome: '欢迎咨询测试服务',
      mockOpening: '请说明服务需求',
      quickReplies: [],
      hardRequirements: '只输出服务正文。',
      identityAnswer: '我是测试服务的 AI 顾问',
      resetReply: '已重新开始',
      resetDisabledReply: '请告诉我新的需求',
      handoffFallback: '顾问会处理',
    },
    templates: {
      identityAnswer: '{identityLine}',
      offTopicReply: '请说明{scopeNoun}需求',
      welcomeText: '欢迎咨询{brandName}',
      welcomeBackText: '欢迎回来，{brandName}为您服务',
      webWelcome: '欢迎咨询{brandName}',
      mockOpening: '请说明{scopeNoun}需求',
      quickReplies: [],
      preamble: '{brandName}',
      pages: {},
    },
    sopSections: [],
    contractRules: () => [],
    knownFields: { names: [], sourceFiles: [] },
    stages: fixture.stages.map((s) => ({ id: s.key as SalesStage })),
    tools: [
      {
        def: {
          type: 'function',
          function: { name: 'fixture_inspect', description: '核验服务需求', parameters: { type: 'object', properties: {} } },
        },
        sideEffects: [],
        cacheable: true,
        blocksRetry: false,
        execute: async () => JSON.stringify({ inspected: true }),
      },
    ],
    extractProfile: () => ({ notes: ['已核验'] }),
    advanceStage: (session, turn) => (turn.calls.some((c) => c.name === 'fixture_inspect') ? 'objection' : session.stage),
    contextNote: () => ['按测试服务规则核验需求'],
    replyAnchors: { markdown: 'fixture_guard' },
    replySteps: [
      {
        id: 'fixture_guard',
        after: ['stage_advance'],
        run(ctx) {
          const text = ctx.text.replace(/测试禁词/g, '已核验');
          if (text === ctx.text) return { action: 'pass' };
          ctx.recordGuard('fixture_guard', ctx.text, text, 'replace');
          return { action: 'replace', text };
        },
      },
    ],
    followupSteps: [],
    engineHooks: {
      isComplaint: () => false,
      isHandoffIntent: () => false,
      safetyNetKind: () => 'request',
      handoffReply: () => '顾问会处理',
      departNoteForHandoff: () => undefined,
      fallbackReply: () => '请告诉我需要核验的内容',
      hintsFor: () => ({}),
      withNotes: (text) => text,
      modelRequestedHandoff: () => false,
      retrievalEmpty: () => false,
      createOrderTool: null,
      resetSession() {},
      paidText: () => '付款已收到',
    },
    vocab: {
      // 空词表让确定性检测不匹配行业内容；算法仍从同一包接口读取。
      handoff: emptyHandoffVocab(),
      dejargon: { english: {}, internal: [] },
    },
    thresholds: {},
    retrievalItems: () => [],
    retrievalCacheFile: 'fixture-vectors.json',
    retrievalText: (item) => JSON.stringify(item.payload),
    followupTemplates: { idleMinutes: {}, byStage: {}, fallback: '需要帮助随时说', system: '写一句服务跟进' },
    insightPrompts: {
      draftFallbackStage: 'greeting',
      stuckStages: [],
      insights: '分析服务',
      suggestion: '给出建议',
      draft: '起草服务回复',
      reach: {},
      funnelNames: [],
      draftFallback: { greeting: '请说明需求' },
    },
    mock: {
      async chat(opts) {
        await opts.executeTool('fixture_inspect', {});
        return '测试禁词：需求已经核验';
      },
    },
  };
}

function emptyHandoffVocab(): PackRuntime['vocab']['handoff'] {
  // 各词表键是固定契约，正则永不匹配；结构从契约列明，不依赖旅游包。
  const never = /(?!) /g;
  return {
    TRAD: {},
    TRAD_RE: never,
    COND: never,
    HEARSAY: never,
    PAST: never,
    PAST_CUT: never,
    HEARSAY_CUT: never,
    NOW_LEAD: never,
    ASKING_TAIL: never,
    ASKING_WORDS: never,
    NOT_A_QUESTION: never,
    NEG_BEFORE: never,
    E_ALTITUDE_MARKER: never,
    E_ALTITUDE_OVERLAP: never,
    EMERGENCY_RULES: [],
    CARELESS: never,
    E_HYPO: never,
    E_PRETRIP: never,
    E_NEAR: never,
    E_HABIT: never,
    E_PRICE: never,
    E_JOKE: never,
    E_POLICY: never,
    E_HEARSAY: never,
    E_NEG_BEFORE: never,
    E_UNSURE: never,
    E_EXAGGERATE: never,
    E_AFTER_SKIP: never,
    E_ATTACHED: never,
    E_HAPPENED_BEFORE: never,
    E_FEVER: never,
    E_NOW: never,
    E_ONGOING: never,
    E_FALL_HURT: never,
    E_FALL_THING: never,
    E_VEHICLE_STUCK: never,
    E_WOUND: never,
    E_FINE_AFTER: never,
    E_TRAPPED_AT: never,
    E_TRAPPED_ABSTRACT: never,
    E_NOT_STUCK: never,
    E_ELSEWHERE: never,
    E_RESCUE_LEAD: never,
    E_HELP: never,
    E_IDENTITY: never,
    E_GREETING: never,
    E_UNKNOWN: never,
    E_ASKING: never,
    E_EVERY: never,
    E_ARRANGE: never,
    COMPANION_PHRASE: never,
    COMPANION_MARK: '\u0000',
    PARTY_MENTION: never,
    OTHER_MENTION: never,
    NOT_SUBJECT_LEAD: never,
    FAMILY_LEAD: never,
    THIRD_PARTY: never,
    ASK_TAIL: never,
    EMBEDDED: never,
    DEPENDS_LEAD: never,
    ASK_WORDS: never,
    EVERY_AFTER: never,
    EVERY_ANOTA_AFTER: never,
    NOT_ASKING_REST: never,
    US: never,
    OWNED_BY_US: never,
    OWNED_KIND: never,
    SELF: never,
    OTHERS: never,
    OBJECT_LEAD: never,
    OTHER_AGENCY: never,
    JOKE: never,
    DOUBT_WORD: never,
    STRONG_DIRECTED: never,
    INSULT: never,
    STUPID: never,
    INSULT_TARGET_AFTER: never,
    INSULT_OBJECT: never,
    BARE_FILLER: never,
    BARE_INSULT: never,
    BROKEN: never,
    INTENSIFIER: never,
    WEAK: never,
    SLOW_PACE: never,
    WEAK_US_BEFORE: never,
    WEAK_RHETORICAL: never,
    REPEAT_SAID: never,
    PEOPLE: never,
    WEAK_DIRECTED: never,
    POSITIVE_BEFORE: never,
    WORRY_BEFORE: never,
    SEG_ASKING: never,
    COMPLAINT_TAG: never,
    ONLY_US: never,
    HEALTH: never,
    PERSON: never,
    CHILD_AGE_AFTER: never,
    CHILD_AGE_BEFORE: never,
    SCHOOL: never,
    CHILD_RE: never,
    WITHDRAW: [],
    POLITE_ASK: never,
    POLICY_ASK: never,
    NOT_WANTED: never,
  };
}
