// 家装整装包：假的，只用来证明界面换一个行业包不需要改 console（docs/features/console-ux/spec.md「行业包通用架构 · 放在哪里」，
// 取值见设计系统 §9.2）。只给自测和走查用：不进注册表，也不进构建产物（不变量 25）；console/src 里只有渲染器自测可以 import 它。
// 不放 src/packs/：那里白名单以外的目录会被公开边界门禁拦下。它的字不进 UI 优先片（scripts/fonts/ui-text.ts 跳过本目录）。
// 纯数据，只 import 类型；由 src/packs/packs.selftest.ts 跑 checkPack（不变量 13）。
// 样例（L 页的 4 件主材、5 个套餐）在同目录的 renovation-samples.json，渲染器自测从那里读；钉 L 页写法的断言用冻结的
// renovation-l-page.ts。往这里加字段时样例跟着补，不用改 console/src（验收 5 第一条）。
// 套餐的「含软装」、主材的「产地」「规格」是 plan 第 17.1 步后加的（验收 5 第一条：加字段不改 console/src），设计系统 §9.2 与 L 页没有。
// 含软装暂时只当筛选、不成列，套餐列表的列仍是 L 页的 8 列：验收 5 两条在它身上相抵，成列还是只当筛选待 owner 定（plan「Open」）。
import type { EntityType, IndustryPack } from '../pack.js';

const pkg: EntityType = {
  kind: 'package',
  label: '装修套餐',
  icon: 'package',
  codeLabel: '套餐编号',
  codeExample: 'p-nuanmu-2r',
  titleKey: 'title',
  subtitleKeys: ['$code'],
  groups: [
    { key: 'basic', label: '基本信息' },
    { key: 'price', label: '价格' },
    { key: 'fit', label: '适合谁' },
    { key: 'terms', label: '施工与条款' },
    { key: 'nodes', label: '施工节点' },
    { key: 'sell', label: '卖点' },
  ],
  lockGroups: {
    id: { tag: '识别', reason: '销售助手靠名称认出业主说的是哪个套餐' },
    price: { tag: '计价', reason: '已发出的估价单按这些数算，改了会变价' },
    terms: { tag: '条款', reason: '已签的合同按这些条款施工' },
    rec: { tag: '推荐', reason: '推荐套餐时按户型筛' },
  },
  fields: [
    { key: '$code', type: 'text', label: '套餐编号', group: 'basic', lockGroup: 'id' },
    { key: 'title', type: 'text', label: '套餐名称', group: 'basic', lockedWhenActive: true, lockGroup: 'id' },
    { key: 'pricePerSqm', type: 'money', unit: '元/㎡', label: '每平米单价', group: 'price', lockedWhenActive: true, lockGroup: 'price' },
    { key: 'minArea', type: 'intUnit', unit: '㎡', label: '起装面积', group: 'price', lockedWhenActive: true, lockGroup: 'price' },
    {
      key: 'houseTypes',
      type: 'enum',
      multiple: true,
      options: ['一居', '两居', '三居', '四居及以上', '别墅'],
      label: '适用户型',
      group: 'fit',
      lockedWhenActive: true,
      lockGroup: 'rec',
    },
    { key: 'styles', type: 'tags', label: '风格', group: 'fit', suggest: ['现代简约', '奶油', '原木', '新中式', '轻法式'] },
    { key: 'startMonths', type: 'monthRange', label: '适合开工月份', group: 'fit', monthMeaning: '施工旺季，排期要提前4周' },
    { key: 'duration', type: 'intUnit', unit: '天', label: '工期', group: 'terms', lockedWhenActive: true, lockGroup: 'terms' },
    {
      key: 'demolition',
      type: 'boolean',
      trueLabel: '含拆旧',
      falseLabel: '不含拆旧',
      label: '拆旧',
      group: 'terms',
      lockedWhenActive: true,
      lockGroup: 'terms',
    },
    {
      key: 'softFurnishing',
      type: 'boolean',
      label: '含软装',
      required: false,
      group: 'terms',
      lockedWhenActive: true,
      lockGroup: 'terms',
    },
    {
      key: 'materials',
      type: 'reference',
      to: 'material',
      store: 'code',
      multiple: true,
      label: '包含主材',
      group: 'terms',
      lockedWhenActive: true,
      lockGroup: 'terms',
    },
    {
      key: 'nodes',
      type: 'subItems',
      label: '施工节点',
      group: 'nodes',
      indexLabel: '节点{n}',
      itemNoun: '个节点',
      item: [
        { key: 'name', type: 'text', label: '节点名称', group: '', placeholder: '例：水电' },
        { key: 'days', type: 'intUnit', unit: '天', label: '工期', group: '' },
        { key: 'checkpoints', type: 'longText', softMax: 80, label: '验收要点', group: '' },
        {
          key: 'materials',
          type: 'reference',
          to: 'material',
          store: 'code',
          multiple: true,
          required: false,
          label: '用到的主材',
          group: '',
        },
      ],
    },
    {
      key: 'highlights',
      type: 'subItems',
      item: [{ key: '', type: 'text', label: '', group: '' }],
      itemNoun: '条',
      label: '卖点',
      group: 'sell',
    },
    { key: '$status', type: 'status', label: '状态', group: 'basic' },
  ],
  list: {
    columns: ['title', 'houseTypes', 'pricePerSqm', 'minArea', 'duration', 'startMonths', '$status', '$updated'],
    filters: ['houseTypes', 'styles', 'softFurnishing'],
    search: ['title', 'styles', '$code'],
    defaultSort: '-$updated',
  },
  csvImport: false,
  activateLine: '上架后，销售助手会向业主推荐这个套餐，并按每平米 {pricePerSqm} 估价',
};

const material: EntityType = {
  kind: 'material',
  label: '主材',
  icon: 'layers',
  codeLabel: '主材编号',
  codeExample: 'm-marcopolo-800',
  titleKey: 'name',
  subtitleKeys: ['category', '$code'],
  groups: [
    { key: 'basic', label: '基本信息' },
    { key: 'price', label: '价格' },
    { key: 'terms', label: '质保与环保' },
  ],
  lockGroups: { price: pkg.lockGroups.price },
  fields: [
    { key: '$code', type: 'text', label: '主材编号', group: 'basic' },
    { key: 'name', type: 'text', label: '主材名称', group: 'basic' },
    { key: 'category', type: 'enum', options: ['瓷砖', '地板', '橱柜', '卫浴', '门窗', '涂料'], label: '品类', group: 'basic' },
    { key: 'brand', type: 'text', label: '品牌', group: 'basic', suggest: 'distinct' },
    { key: 'origin', type: 'text', label: '产地', group: 'basic', suggest: 'distinct', placeholder: '例：广东佛山' },
    {
      key: 'specs',
      type: 'subItems',
      item: [{ key: '', type: 'text', label: '', group: '', placeholder: '例：800×800' }],
      itemNoun: '种',
      label: '规格',
      group: 'basic',
    },
    {
      key: 'priceUnit',
      type: 'enum',
      options: ['㎡', '延米', '件', '套'],
      label: '计价单位',
      group: 'price',
      lockedWhenActive: true,
      lockGroup: 'price',
    },
    { key: 'unitPrice', type: 'money', unitFrom: 'priceUnit', label: '单价', group: 'price', lockedWhenActive: true, lockGroup: 'price' },
    { key: 'warrantyYears', type: 'intUnit', unit: '年', label: '质保', group: 'terms' },
    { key: 'ecoGrade', type: 'enum', options: ['ENF级', 'E0级', 'E1级'], label: '环保等级', required: false, group: 'terms' },
    { key: '$status', type: 'status', label: '状态', group: 'basic' },
  ],
  list: {
    columns: ['name', 'category', 'brand', 'origin', 'specs', 'unitPrice', 'warrantyYears', '$status', '$updated'],
    filters: ['category', 'origin'],
    search: ['name', 'brand', '$code'],
    defaultSort: '-$updated',
  },
  csvImport: true,
  activateLine: '上架后，套餐和销售助手可以引用这件主材，按 {unitPrice} 计价',
};

export const renovation: IndustryPack = {
  id: 'renovation',
  name: '家装整装',
  vocabulary: {
    customer: '业主',
    advisor: '设计顾问',
    productNoun: '产品',
    tools: {
      search_packages: '查套餐',
      get_package_detail: '看套餐详情',
      search_materials: '查主材',
      create_estimate: '算估价',
      book_measure: '预约量房',
      handoff_to_human: '转人工',
    },
    sopFields: { pricePerSqm: '每平米单价', minArea: '起装面积', measureSlot: '量房时段' },
  },
  stages: [
    { key: 'consult', label: '咨询' },
    { key: 'measure', label: '量房' },
    { key: 'design', label: '方案' },
    { key: 'quote', label: '报价' },
    { key: 'sign', label: '签约' },
    { key: 'deposit', label: '已付定金', terminal: true },
  ],
  sopSections: [
    { key: 'preamble', heading: null, locked: false },
    { key: 'stages', heading: '各阶段目标', locked: true, lockReason: '量房、出方案、报价的顺序由代码核对' },
    { key: 'tone', heading: '话术原则', locked: false },
    { key: 'pricing', heading: '报价规则（硬性）', locked: true, lockReason: '和算估价工具是同一套规则' },
    { key: 'measure', heading: '量房预约规则', locked: true, lockReason: '可约时段来自预约工具' },
    { key: 'objections', heading: '异议处理', locked: false },
    { key: 'capabilities', heading: '能力边界（硬性）', locked: true, lockReason: '工期和增项承诺由代码守' },
    { key: 'handoff', heading: '转人工条件', locked: true, lockReason: '要和系统的转人工判断一致' },
    { key: 'wechat-style', heading: '微信语气规范', locked: false },
  ],
  nav: { catalogGroup: '产品库', entities: ['package', 'material'] },
  entities: [pkg, material],
};
