// 旅游包的界面配置（docs/features/console-ux/spec.md「行业包通用架构」，取值见设计系统 §9.1）。
// 纯数据，只 import 类型：取值照抄真实代码（各处注释写了出处），由 src/packs/packs.selftest.ts 逐项核对（不变量 14，plan 第 3.1 步）。
// 这里的标签、帮助、原因都会显示在后台上，也是 UI 优先片的用字来源（scripts/fonts/ui-text.ts）：改了文案要重跑 scripts/fonts/build.ts。
import type { EntityType, IndustryPack } from '../../shared/pack.js';

// 锁定表来自 src/shared/catalog.ts 的 LOCKED_WHEN_ACTIVE；字段来自 data/routes.json 与 RouteSchema
const route: EntityType = {
  kind: 'route',
  label: '线路',
  icon: 'route',
  codeLabel: '线路编号',
  codeExample: 'r-sichuan-lux',
  titleKey: 'title',
  subtitleKeys: ['destination', '$code'],
  groups: [
    { key: 'basic', label: '基本信息' },
    { key: 'price', label: '价格与季节' },
    { key: 'fit', label: '适合谁去' },
    { key: 'days', label: '逐日行程' },
    { key: 'terms', label: '费用包含与不含' },
    { key: 'sell', label: '卖点' },
    { key: 'alias', label: '客户怎么叫' },
  ],
  // 计价与条款两组（每人起价、最佳季节、费用包含与不含）02 有了条目版本之后不再锁：改了只影响之后的报价和方案书
  lockGroups: {
    id: { tag: '识别', reason: '销售助手靠这些认出客户说的是哪条线，改名会让对话里的旧说法认不出来' },
    rec: { tag: '推荐', reason: '推荐和安全护栏按这些筛线路，包括给长辈换低海拔线路、区分境内外' },
  },
  fields: [
    {
      key: '$code',
      type: 'text',
      label: '线路编号',
      group: 'basic',
      lockGroup: 'id', // 永远只读（ALWAYS_LOCKED）
      help: '小写字母、数字和连字符，建好后不能改',
      placeholder: '例：r-sichuan-lux',
    },
    {
      key: 'title',
      type: 'text',
      label: '线路名称',
      group: 'basic',
      lockedWhenActive: true,
      lockGroup: 'id',
      help: '写上目的地和天数',
      placeholder: '例：四川 稻城亚丁·色达秘境 8 日',
    },
    {
      key: 'destination',
      type: 'text',
      label: '目的地',
      group: 'basic',
      lockedWhenActive: true,
      lockGroup: 'id',
      suggest: 'distinct',
      help: '客户问「去哪」时按它匹配',
    },
    {
      key: 'days',
      type: 'intUnit',
      unit: '天',
      min: 1,
      max: 30,
      label: '天数',
      group: 'basic',
      lockedWhenActive: true,
      lockGroup: 'id',
      help: '要和逐日行程的天数一样',
    },
    {
      key: 'overseas',
      type: 'boolean',
      trueLabel: '境外',
      falseLabel: '境内',
      label: '境内还是境外',
      group: 'fit',
      lockedWhenActive: true,
      lockGroup: 'rec',
      help: '推荐和报价按它区分境内外',
    },
    {
      key: 'priceFrom',
      type: 'money',
      unit: '元/人',
      label: '每人起价',
      group: 'price',
      reprices: true,
      help: '填淡季、4人以下的价；旺季上浮10%、4人及以上95折由系统算',
    },
    {
      key: 'bestSeason',
      type: 'monthRange',
      label: '最佳季节',
      group: 'price',
      reprices: true,
      monthMeaning: '这些月份出发报价上浮10%，「全年」不加价',
      yearRoundLabel: '全年（不加价）',
    },
    {
      key: 'segments',
      type: 'enum',
      multiple: true,
      min: 1,
      options: ['家庭', '亲子', '蜜月', '商务', '银发'],
      label: '适合客群',
      group: 'fit',
      lockedWhenActive: true,
      lockGroup: 'rec',
      help: '可多选，推荐线路时按它筛',
    },
    {
      key: 'maxAltitude',
      type: 'intUnit',
      unit: '米',
      label: '全程最高海拔',
      required: false,
      recommend: true,
      group: 'fit',
      lockedWhenActive: true,
      lockGroup: 'rec',
      help: '按行程核实的最高点，给长辈挑线路时只看这个数',
    },
    {
      key: 'intensity.level',
      type: 'enum',
      options: ['轻松', '适中', '较累'],
      label: '体力强度',
      required: false,
      recommend: true,
      group: 'fit',
      help: '看最累的那天',
    },
    {
      key: 'intensity.hardest',
      type: 'text',
      label: '最累的一段',
      group: 'fit',
      showWhen: { key: 'intensity.level', filled: true },
      help: '照行程原文概括；行程没写步行量就写「行程没写」',
    },
    {
      key: 'itinerary',
      type: 'subItems',
      label: '逐日行程',
      group: 'days',
      countFrom: 'days',
      autoIndexKey: 'day',
      indexLabel: 'D{n}',
      itemNoun: '天',
      item: [
        { key: 'title', type: 'text', label: '当天标题', group: '', placeholder: '例：成都 → 丹巴' },
        { key: 'detail', type: 'longText', label: '当天安排', group: '', softMax: 120, help: '客户在手机上看，写清距离和用时' },
        {
          key: 'hotel',
          type: 'reference',
          to: 'hotel',
          store: 'label',
          allowFree: true,
          filterBy: 'destination',
          label: '当晚住宿',
          group: '',
          help: '最后一天可以写「—（返程）」',
        },
        {
          key: 'meals',
          type: 'enum',
          multiple: true,
          options: ['早', '午', '晚'],
          storeAs: { join: '/', empty: '—' },
          label: '当天餐食',
          group: '',
        },
      ],
    },
    {
      key: 'inclusions',
      type: 'subItems',
      item: [{ key: '', type: 'text', label: '', group: '' }],
      itemNoun: '条',
      label: '费用包含',
      required: false,
      recommend: true,
      group: 'terms',
      reprices: true,
    },
    {
      key: 'exclusions',
      type: 'subItems',
      item: [{ key: '', type: 'text', label: '', group: '' }],
      itemNoun: '条',
      label: '费用不含',
      required: false,
      recommend: true,
      group: 'terms',
      reprices: true,
    },
    { key: 'hotelLevel', type: 'text', label: '住宿档次', group: 'sell', suggest: 'distinct', placeholder: '例：顶级野奢' },
    {
      key: 'highlights',
      type: 'subItems',
      item: [{ key: '', type: 'text', label: '', group: '' }],
      itemNoun: '条',
      label: '行程亮点',
      group: 'sell',
      min: 1,
      recommend: { min: 3, max: 5 },
      help: '建议3–5条，每条以动词开头',
    },
    {
      key: 'tags',
      type: 'tags',
      label: '标签',
      group: 'sell',
      lockedWhenActive: { members: ['国内'] },
      lockGroup: 'rec',
      help: '其中「国内」上架后锁定',
    },
    {
      key: 'aliases',
      type: 'tags',
      label: '客户的其他叫法',
      required: false,
      recommend: true,
      group: 'alias',
      lockedWhenActive: true,
      lockGroup: 'id',
      help: '标题和目的地里没有、客户常说的叫法，如「川西」',
    },
    { key: '$status', type: 'status', label: '状态', group: 'basic' },
  ],
  list: {
    columns: ['title', 'days', 'priceFrom', 'bestSeason', 'segments', '$status', '$updated'],
    filters: ['destination', 'overseas', 'segments'],
    search: ['title', 'destination', 'aliases', '$code'],
    defaultSort: '-$updated',
  },
  csvImport: false,
  activateLine: '上架后，销售助手会立即向客户推荐这条线路，并按每人 {priceFrom} 起报价',
};

const hotel: EntityType = {
  kind: 'hotel',
  label: '酒店',
  icon: 'bed-double',
  codeLabel: '酒店编号',
  codeExample: 'h-songtsam-meili',
  titleKey: 'name',
  subtitleKeys: ['destination', '$code'],
  groups: [
    { key: 'basic', label: '基本信息' },
    { key: 'price', label: '价格' },
    { key: 'sell', label: '卖点' },
  ],
  // 每晚起价 02 有了条目版本之后不再锁（同线路的计价组）
  lockGroups: {
    id: { tag: '识别', reason: '销售助手靠这些认出客户说的是哪家酒店，改名会让对话里的旧说法认不出来' },
  },
  fields: [
    { key: '$code', type: 'text', label: '酒店编号', group: 'basic', lockGroup: 'id' },
    { key: 'name', type: 'text', label: '酒店名称', group: 'basic', lockedWhenActive: true, lockGroup: 'id' },
    { key: 'destination', type: 'text', label: '目的地', group: 'basic', lockedWhenActive: true, lockGroup: 'id', suggest: 'distinct' },
    { key: 'stars', type: 'text', label: '星级档次', group: 'basic', suggest: 'distinct', placeholder: '例：五星、顶奢' },
    { key: 'nightlyFrom', type: 'money', unit: '元/晚', label: '每晚起价', group: 'price', reprices: true },
    { key: 'roomType', type: 'text', label: '主推房型', group: 'sell', placeholder: '例：水上别墅' },
    {
      key: 'highlights',
      type: 'subItems',
      item: [{ key: '', type: 'text', label: '', group: '' }],
      itemNoun: '条',
      label: '酒店亮点',
      group: 'sell',
      min: 1,
    },
    { key: 'tags', type: 'tags', label: '标签', group: 'sell' }, // 必填只要求键存在，可以是 []（HotelSchema 的 tags: texts）
    { key: '$status', type: 'status', label: '状态', group: 'basic' },
  ],
  list: {
    columns: ['name', 'stars', 'nightlyFrom', 'roomType', 'tags', '$status', '$updated'],
    filters: ['destination'],
    search: ['name', 'destination', '$code'],
    defaultSort: '-$updated',
  },
  csvImport: true,
  activateLine: '上架后，销售助手会向客户推荐这家酒店，并按每晚 {nightlyFrom} 起介绍',
};

export const travel: IndustryPack = {
  id: 'travel',
  name: '旅游',
  vocabulary: {
    customer: '客户',
    advisor: '顾问',
    productNoun: '产品',
    // src/tool-defs.ts
    tools: {
      search_routes: '查线路',
      get_route_detail: '看线路详情',
      search_hotels: '查酒店',
      create_quote: '算报价',
      generate_proposal: '生成方案书',
      create_order: '下单',
      handoff_to_human: '转人工',
    },
    // src/sop/contract.ts 的 SOP_KNOWN_FIELDS
    sopFields: {
      altitudeNote: '海拔提示',
      bestSeason: '最佳季节',
      departDate: '出发日期',
      destinationMiss: '没有的目的地',
      intensityNote: '强度提示',
      maxBudgetPerPerson: '每人预算上限',
      maxNightlyPrice: '每晚预算上限',
      overBudget: '超出预算',
      payUrl: '付款链接',
      priceFrom: '起价',
      routeId: '线路编号',
      supersededOrderId: '作废的订单',
      withinBudget: '在预算内',
    },
  },
  // src/types.ts 的 SalesStage。'handoff' 不算阶段，它对应会话状态「等人接手」
  stages: [
    { key: 'greeting', label: '开场' },
    { key: 'discovery', label: '问需' },
    { key: 'recommend', label: '推荐' },
    { key: 'quote', label: '报价' },
    { key: 'objection', label: '异议', branchOf: 'quote' },
    { key: 'closing', label: '促成' },
    { key: 'paid', label: '已支付', terminal: true },
  ],
  // src/sop/sections.ts 的 TRAVEL_SOP_SECTIONS；原因照 01 spec 的「节表」改写成人话
  sopSections: [
    { key: 'preamble', heading: null, locked: false },
    { key: 'stages', heading: '各阶段目标', locked: true, lockReason: '报价时机、出方案书、细节只按原文答，这些做法由代码逐条核对' },
    { key: 'orders', heading: '订单：改单、给别人再订、重发链接', locked: true, lockReason: '改单时作废旧订单的做法和下单工具绑在一起' },
    { key: 'tone', heading: '话术原则', locked: false },
    {
      key: 'quote-discipline',
      heading: '报价纪律（硬性）',
      locked: true,
      lockReason: '超出预算怎么说、按总价比预算，和算报价工具绑在一起',
    },
    {
      key: 'price-rules',
      heading: '定价规则（只有这两条，硬性）',
      locked: true,
      lockReason: '和算报价、价格护栏是同一套规则，改了会报出和系统不一致的价',
    },
    { key: 'objections', heading: '异议处理', locked: false },
    {
      key: 'capabilities',
      heading: '能力边界（硬性，先看这条）',
      locked: true,
      lockReason: '天数和住宿固定、顾问在微信上联系，这些承诺由代码守',
    },
    {
      key: 'no-destinations',
      heading: '我们没有的目的地（如南极、冰岛）',
      locked: true,
      lockReason: '没有的目的地怎么回、坚持才转人工，由代码判断',
    },
    {
      key: 'handoff',
      heading: '转人工条件（满足任一立即调用 handoff_to_human）',
      locked: true,
      lockReason: '什么时候转人工，要和系统的转人工判断一致',
    },
    { key: 'wechat-style', heading: '微信语气规范', locked: false },
  ],
  nav: { catalogGroup: '产品库', entities: ['route', 'hotel'] },
  entities: [route, hotel],
};
